import type { Professional, Client, Service, Appointment, Product, FinancialEntry, WaitlistEntry, SubscriptionPlan } from './types'

export const professionals: Professional[] = [
  {
    id: '1',
    name: 'Carlos Silva',
    email: 'carlos@barbearia.com',
    phone: '(11) 99999-1111',
    nickname: 'Carlos',
    avatar: '',
    status: 'active',
    services: ['1', '2', '3', '4'],
    workingHours: [
      { dayOfWeek: 1, blocks: [{ id: '1a', startTime: '09:00', endTime: '12:00' }, { id: '1b', startTime: '13:00', endTime: '18:00' }] },
      { dayOfWeek: 2, blocks: [{ id: '2a', startTime: '09:00', endTime: '12:00' }, { id: '2b', startTime: '13:00', endTime: '18:00' }] },
      { dayOfWeek: 3, blocks: [{ id: '3a', startTime: '09:00', endTime: '12:00' }, { id: '3b', startTime: '13:00', endTime: '18:00' }] },
      { dayOfWeek: 4, blocks: [{ id: '4a', startTime: '09:00', endTime: '12:00' }, { id: '4b', startTime: '13:00', endTime: '18:00' }] },
      { dayOfWeek: 5, blocks: [{ id: '5a', startTime: '09:00', endTime: '12:00' }, { id: '5b', startTime: '13:00', endTime: '18:00' }] },
      { dayOfWeek: 6, blocks: [{ id: '6a', startTime: '09:00', endTime: '14:00' }] },
    ],
  },
  {
    id: '2',
    name: 'Pedro Oliveira',
    email: 'pedro@barbearia.com',
    phone: '(11) 99999-2222',
    nickname: 'Pedro',
    avatar: '',
    status: 'active',
    services: ['1', '2', '5'],
    workingHours: [
      { dayOfWeek: 1, blocks: [{ id: '7a', startTime: '10:00', endTime: '13:00' }, { id: '7b', startTime: '14:00', endTime: '19:00' }] },
      { dayOfWeek: 2, blocks: [{ id: '8a', startTime: '10:00', endTime: '13:00' }, { id: '8b', startTime: '14:00', endTime: '19:00' }] },
      { dayOfWeek: 3, blocks: [{ id: '9a', startTime: '10:00', endTime: '13:00' }, { id: '9b', startTime: '14:00', endTime: '19:00' }] },
      { dayOfWeek: 4, blocks: [{ id: '10a', startTime: '10:00', endTime: '13:00' }, { id: '10b', startTime: '14:00', endTime: '19:00' }, { id: '10c', startTime: '20:00', endTime: '22:00' }] },
      { dayOfWeek: 5, blocks: [{ id: '11a', startTime: '10:00', endTime: '13:00' }, { id: '11b', startTime: '14:00', endTime: '19:00' }] },
    ],
  },
  {
    id: '3',
    name: 'Ana Beatriz',
    email: 'ana@barbearia.com',
    phone: '(11) 99999-3333',
    nickname: 'Ana',
    avatar: '',
    status: 'active',
    services: ['2', '4', '6', '7'],
    workingHours: [
      { dayOfWeek: 2, blocks: [{ id: '12a', startTime: '09:00', endTime: '12:00' }, { id: '12b', startTime: '13:00', endTime: '18:00' }] },
      { dayOfWeek: 3, blocks: [{ id: '13a', startTime: '09:00', endTime: '12:00' }, { id: '13b', startTime: '13:00', endTime: '18:00' }] },
      { dayOfWeek: 4, blocks: [{ id: '14a', startTime: '09:00', endTime: '12:00' }, { id: '14b', startTime: '13:00', endTime: '18:00' }] },
      { dayOfWeek: 5, blocks: [{ id: '15a', startTime: '09:00', endTime: '12:00' }, { id: '15b', startTime: '13:00', endTime: '18:00' }] },
      { dayOfWeek: 6, blocks: [{ id: '16a', startTime: '09:00', endTime: '16:00' }] },
    ],
  },
]

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: 'plan-1',
    name: 'Premium',
    description: 'Plano premium com 2 cortes por semana',
    price: 150,
    usageLimit: 2,
    allowedDays: [4, 5], // Quinta e Sexta
    services: ['1', '2'], // Corte e Barba
    isActive: true,
  },
  {
    id: 'plan-2',
    name: 'Premium Plus',
    description: 'Plano premium plus com 2 cortes por semana',
    price: 200,
    usageLimit: 2,
    allowedDays: [3, 6], // Quarta e Sábado
    services: ['1', '2', '3'], // Corte, Barba e Combo
    isActive: true,
  },
  {
    id: 'plan-3',
    name: 'Basic',
    description: 'Plano básico com 1 corte por semana',
    price: 80,
    usageLimit: 1,
    allowedDays: [1, 2, 3, 4, 5], // Segunda a Sexta
    services: ['1'], // Apenas Corte
    isActive: true,
  },
  {
    id: 'plan-4',
    name: 'VIP',
    description: 'Plano VIP ilimitado',
    price: 350,
    usageLimit: 7,
    allowedDays: [0, 1, 2, 3, 4, 5, 6], // Todos os dias
    services: ['1', '2', '3', '4', '5', '6', '7'], // Todos os serviços
    isActive: true,
  },
]

export const clients: Client[] = [
  {
    id: '1',
    name: 'João Santos',
    email: 'joao@email.com',
    phone: '(11) 98888-1111',
    birthDate: '1990-05-15',
    gender: 'male',
    cpf: '123.456.789-00',
    points: 150,
    status: 'active',
    createdAt: '2024-01-10',
    address: {
      zipCode: '01310-100',
      street: 'Av. Paulista',
      number: '1000',
      neighborhood: 'Bela Vista',
      city: 'São Paulo',
      state: 'SP',
    },
    subscription: {
      planId: 'plan-1',
      startDate: '2024-01-15',
      usedThisWeek: 1,
      lastResetDate: '2024-05-06',
    },
  },
  {
    id: '2',
    name: 'Maria Oliveira',
    email: 'maria@email.com',
    phone: '(11) 98888-2222',
    birthDate: '1985-08-22',
    gender: 'female',
    cpf: '234.567.890-11',
    points: 280,
    status: 'active',
    createdAt: '2024-01-05',
    subscription: {
      planId: 'plan-2',
      startDate: '2024-02-01',
      usedThisWeek: 2,
      lastResetDate: '2024-05-06',
    },
  },
  {
    id: '3',
    name: 'Lucas Mendes',
    email: 'lucas@email.com',
    phone: '(11) 98888-3333',
    birthDate: '1995-12-01',
    gender: 'male',
    points: 50,
    status: 'active',
    createdAt: '2024-02-15',
  },
  {
    id: '4',
    name: 'Fernanda Costa',
    email: 'fernanda@email.com',
    phone: '(11) 98888-4444',
    gender: 'female',
    points: 320,
    status: 'active',
    createdAt: '2023-11-20',
  },
  {
    id: '5',
    name: 'Ricardo Almeida',
    email: 'ricardo@email.com',
    phone: '(11) 98888-5555',
    birthDate: '1988-03-10',
    gender: 'male',
    points: 90,
    status: 'inactive',
    createdAt: '2024-01-25',
  },
]

export const services: Service[] = [
  {
    id: '1',
    name: 'Corte Masculino',
    description: 'Corte de cabelo masculino tradicional',
    duration: 30,
    price: 45.00,
    commission: 40,
    category: 'Cabelo',
    isAvailable: true,
  },
  {
    id: '2',
    name: 'Barba',
    description: 'Barba completa com toalha quente',
    duration: 20,
    price: 30.00,
    commission: 40,
    category: 'Barba',
    isAvailable: true,
  },
  {
    id: '3',
    name: 'Corte + Barba',
    description: 'Combo corte masculino e barba',
    duration: 45,
    price: 65.00,
    commission: 40,
    category: 'Combo',
    isAvailable: true,
  },
  {
    id: '4',
    name: 'Sobrancelha',
    description: 'Design de sobrancelha',
    duration: 15,
    price: 20.00,
    commission: 35,
    category: 'Estética',
    isAvailable: true,
  },
  {
    id: '5',
    name: 'Relaxamento',
    description: 'Tratamento capilar relaxante',
    duration: 60,
    price: 80.00,
    commission: 45,
    category: 'Tratamento',
    isAvailable: true,
  },
  {
    id: '6',
    name: 'Coloração',
    description: 'Coloração capilar profissional',
    duration: 90,
    price: 120.00,
    commission: 35,
    category: 'Tratamento',
    isAvailable: true,
  },
  {
    id: '7',
    name: 'Hidratação',
    description: 'Hidratação profunda',
    duration: 45,
    price: 50.00,
    commission: 35,
    category: 'Tratamento',
    isAvailable: true,
  },
]

// Generate appointments for today
const today = new Date()
const formatDate = (date: Date) => date.toISOString().split('T')[0]

export const appointments: Appointment[] = [
  {
    id: '1',
    clientId: '1',
    clientName: 'João Santos',
    professionalId: '1',
    professionalName: 'Carlos Silva',
    serviceId: '3',
    serviceName: 'Corte + Barba',
    date: formatDate(today),
    startTime: '09:00',
    endTime: '09:45',
    status: 'confirmed',
    price: 65.00,
  },
  {
    id: '2',
    clientId: '2',
    clientName: 'Maria Oliveira',
    professionalId: '3',
    professionalName: 'Ana Beatriz',
    serviceId: '6',
    serviceName: 'Coloração',
    date: formatDate(today),
    startTime: '09:00',
    endTime: '10:30',
    status: 'confirmed',
    price: 120.00,
  },
  {
    id: '3',
    clientId: '3',
    clientName: 'Lucas Mendes',
    professionalId: '2',
    professionalName: 'Pedro Oliveira',
    serviceId: '1',
    serviceName: 'Corte Masculino',
    date: formatDate(today),
    startTime: '10:00',
    endTime: '10:30',
    status: 'pending',
    price: 45.00,
  },
  {
    id: '4',
    clientId: '4',
    clientName: 'Fernanda Costa',
    professionalId: '1',
    professionalName: 'Carlos Silva',
    serviceId: '1',
    serviceName: 'Corte Masculino',
    date: formatDate(today),
    startTime: '10:00',
    endTime: '10:30',
    status: 'confirmed',
    price: 45.00,
  },
  {
    id: '5',
    clientId: '1',
    clientName: 'João Santos',
    professionalId: '2',
    professionalName: 'Pedro Oliveira',
    serviceId: '2',
    serviceName: 'Barba',
    date: formatDate(today),
    startTime: '11:00',
    endTime: '11:20',
    status: 'pending',
    price: 30.00,
  },
  {
    id: '6',
    clientId: '5',
    clientName: 'Ricardo Almeida',
    professionalId: '3',
    professionalName: 'Ana Beatriz',
    serviceId: '7',
    serviceName: 'Hidratação',
    date: formatDate(today),
    startTime: '11:00',
    endTime: '11:45',
    status: 'confirmed',
    price: 50.00,
  },
  {
    id: '7',
    clientId: '2',
    clientName: 'Maria Oliveira',
    professionalId: '1',
    professionalName: 'Carlos Silva',
    serviceId: '4',
    serviceName: 'Sobrancelha',
    date: formatDate(today),
    startTime: '14:00',
    endTime: '14:15',
    status: 'confirmed',
    price: 20.00,
  },
  {
    id: '8',
    clientId: '3',
    clientName: 'Lucas Mendes',
    professionalId: '2',
    professionalName: 'Pedro Oliveira',
    serviceId: '3',
    serviceName: 'Corte + Barba',
    date: formatDate(today),
    startTime: '14:00',
    endTime: '14:45',
    status: 'cancelled',
    price: 65.00,
  },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Pomada Modeladora',
    brand: 'Don Juan',
    category: 'Finalização',
    quantity: 25,
    minQuantity: 10,
    price: 45.00,
    professionalPrice: 35.00,
    commission: 20,
    barcode: '7891234567890',
    unit: 'un',
    isAvailable: true,
    forInternalUse: false,
  },
  {
    id: '2',
    name: 'Gel Fixação Forte',
    brand: 'Bozzano',
    category: 'Finalização',
    quantity: 18,
    minQuantity: 10,
    price: 25.00,
    professionalPrice: 18.00,
    commission: 20,
    barcode: '7891234567891',
    unit: 'un',
    isAvailable: true,
    forInternalUse: false,
  },
  {
    id: '3',
    name: 'Shampoo Anticaspa',
    brand: 'Clear',
    category: 'Cabelo',
    quantity: 8,
    minQuantity: 10,
    price: 35.00,
    professionalPrice: 28.00,
    commission: 15,
    unit: 'un',
    isAvailable: true,
    forInternalUse: false,
  },
  {
    id: '4',
    name: 'Óleo para Barba',
    brand: 'Barba Forte',
    category: 'Barba',
    quantity: 12,
    minQuantity: 5,
    price: 55.00,
    professionalPrice: 40.00,
    commission: 25,
    unit: 'un',
    isAvailable: true,
    forInternalUse: false,
  },
  {
    id: '5',
    name: 'Pós-Barba',
    brand: 'Nivea',
    category: 'Barba',
    quantity: 3,
    minQuantity: 5,
    price: 32.00,
    professionalPrice: 25.00,
    commission: 20,
    unit: 'un',
    isAvailable: true,
    forInternalUse: true,
  },
]

export const financialEntries: FinancialEntry[] = [
  {
    id: '1',
    type: 'income',
    description: 'Corte + Barba - João Santos',
    amount: 65.00,
    date: formatDate(today),
    category: 'Serviço',
    paymentMethod: 'PIX',
    professionalId: '1',
    appointmentId: '1',
  },
  {
    id: '2',
    type: 'income',
    description: 'Coloração - Maria Oliveira',
    amount: 120.00,
    date: formatDate(today),
    category: 'Serviço',
    paymentMethod: 'Cartão Crédito',
    professionalId: '3',
    appointmentId: '2',
  },
  {
    id: '3',
    type: 'expense',
    description: 'Compra de produtos',
    amount: 350.00,
    date: formatDate(today),
    category: 'Estoque',
    paymentMethod: 'Transferência',
  },
  {
    id: '4',
    type: 'income',
    description: 'Venda Pomada Modeladora',
    amount: 45.00,
    date: formatDate(today),
    category: 'Produto',
    paymentMethod: 'Dinheiro',
  },
  {
    id: '5',
    type: 'expense',
    description: 'Conta de luz',
    amount: 280.00,
    date: formatDate(new Date(today.getTime() - 86400000)),
    category: 'Despesa Fixa',
    paymentMethod: 'Débito Automático',
  },
]

export const waitlist: WaitlistEntry[] = [
  {
    id: '1',
    clientId: '4',
    clientName: 'Fernanda Costa',
    phone: '(11) 98888-4444',
    serviceId: '5',
    serviceName: 'Relaxamento',
    preferredDate: formatDate(today),
    notes: 'Preferência por horário da tarde',
    createdAt: formatDate(new Date(today.getTime() - 3600000)),
  },
  {
    id: '2',
    clientId: '5',
    clientName: 'Ricardo Almeida',
    phone: '(11) 98888-5555',
    serviceId: '3',
    serviceName: 'Corte + Barba',
    createdAt: formatDate(new Date(today.getTime() - 7200000)),
  },
]

// Helper function to get available time slots
export function getTimeSlots(startHour = 7, endHour = 23, interval = 15): string[] {
  const slots: string[] = []
  for (let hour = startHour; hour <= endHour; hour++) {
    for (let min = 0; min < 60; min += interval) {
      if (hour === endHour && min > 0) break
      slots.push(`${hour.toString().padStart(2, '0')}:${min.toString().padStart(2, '0')}`)
    }
  }
  return slots
}

export const timeSlots = getTimeSlots()

export const serviceCategories = ['Cabelo', 'Barba', 'Combo', 'Estética', 'Tratamento']

export const productCategories = ['Finalização', 'Cabelo', 'Barba', 'Tratamento', 'Acessórios']

export const paymentMethods = ['Dinheiro', 'PIX', 'Cartão Crédito', 'Cartão Débito', 'Transferência']
